### ISSUE TITLE
add roadmap

### ISSUE THREAD

**Issue by jamesturk** [openstates/documentation#54]
killing off the meta repo, let's put this up somewhere so people can follow along/help out

Top Priorities:
- 2019 session/election switchover - Q1
- new OpenStates.org - Q2
- vote data quality push (tools/scraper fixes/etc.) - Q2/3
- gathering full text - Q2
- full text search - Q2/3
- API v2 improvements - ongoing

Others:
- notifications
- evaluation of people scraper transition

**Comment by jamesturk** [comment]
2018 for good measure
January
- [x] redo geo server
- [x] focus on state sessions

February
- [x] scraper improvements


May
- [x] DQ Tools On Alpha

June
- [x] Open States API v2 beta

Q3/Q4
- [x] Change pupa->billy flow to come from DB
- [x] OS ID mapping solution
- [ ] Open States API v2 final
- [ ] new OS.org alpha available
- evaluate mapping API v1 calls to v2
- full text search
- notifications
